development:
  adapter: mysql
  database: newsuck_development
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  database: newsuck_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  database: newsuck_production
  username: root
  password:
  host: localhost
